apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: swiftdrop-prod
  region: us-east-1
  version: "1.30"

vpc:
  # blank to let eksctl create a high-availability VPC across AZs
  nat:
    gateway: Single

nodeGroups:
  - name: ng-standard
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        autoScaler: true
        albIngress: true
